/*
 * Metadata Store API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Rating struct {

	ID int32 `json:"ID,omitempty"`

	MethodType *MethodType `json:"MethodType,omitempty"`

	MethodTypeID int32 `json:"MethodTypeID,omitempty"`

	Score float64 `json:"Score,omitempty"`

	Severity string `json:"Severity,omitempty"`

	Vector string `json:"Vector,omitempty"`
}
