/*
 * Metadata Store API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// NullTime implements the Scanner interface so it can be used as a scan destination, similar to NullString.
type NullTime struct {

	Time time.Time `json:"Time,omitempty"`

	Valid bool `json:"Valid,omitempty"`
}
