/*
 * Metadata Store API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Image struct {

	Digest string `json:"Digest"`

	ID int32 `json:"ID,omitempty"`

	Name string `json:"Name"`

	Packages []ModelPackage `json:"Packages,omitempty"`

	Registry string `json:"Registry"`

	Sources []Source `json:"Sources,omitempty"`
}
