/*
 * Metadata Store API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type MethodType struct {

	CreatedAt time.Time `json:"CreatedAt,omitempty"`

	DeletedAt *DeletedAt `json:"DeletedAt,omitempty"`

	ID int32 `json:"ID,omitempty"`

	Name string `json:"Name,omitempty"`

	Rating []Rating `json:"Rating,omitempty"`

	UpdatedAt time.Time `json:"UpdatedAt,omitempty"`
}
