/*
 * Metadata Store API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Source struct {

	DeletedAt *DeletedAt `json:"DeletedAt,omitempty"`

	Host string `json:"Host,omitempty"`

	ID int32 `json:"ID,omitempty"`

	Images []Image `json:"Images,omitempty"`

	Organization string `json:"Organization,omitempty"`

	Packages []ModelPackage `json:"Packages,omitempty"`

	Repository string `json:"Repository"`

	Sha string `json:"Sha"`
}
