/*
 * Metadata Store API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Model a basic GoLang struct which includes the following fields: ID, CreatedAt, UpdatedAt, DeletedAt It may be embedded into your model or you may build your own model without it type User struct { gorm.Model }
type Model struct {
	CreatedAt time.Time `json:"CreatedAt,omitempty"`
	DeletedAt *DeletedAt `json:"DeletedAt,omitempty"`
	ID int32 `json:"ID,omitempty"`
	UpdatedAt time.Time `json:"UpdatedAt,omitempty"`
}
