/*
 * Metadata Store API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// ErrorMessage wraps an error message in a struct so responses are properly marshalled as a JSON object.
type ErrorMessage struct {
	// in: body
	Message string `json:"message,omitempty"`
}
